val lookup_age_band = sqlContext.read.format("com.databricks.spark.csv").option("header", "true").option("inferSchema", "true").load("/road_safety/datasets/lookups/Age_Band.csv")
lookup_age_band.write.format("orc").saveAsTable("Age_Band")
val lookup_Vehicle_Type = sqlContext.read.format("com.databricks.spark.csv").option("header", "true").option("inferSchema", "true").load("/road_safety/datasets/lookups/Vehicle_Type.csv")
lookup_Vehicle_Type.write.format("orc").saveAsTable("lookup_vehicle_types")
val lookup_Casualty_Severity = sqlContext.read.format("com.databricks.spark.csv").option("header", "true").option("inferSchema", "true").load("/road_safety/datasets/lookups/Casualty_Severity.csv")
lookup_Casualty_Severity.write.format("orc").saveAsTable("Casualty_severity")
val lookup_Sex_of_Casualty = sqlContext.read.format("com.databricks.spark.csv").option("header", "true").option("inferSchema", "true").load("/road_safety/datasets/lookups/Sex_of_Casualty.csv")
lookup_Sex_of_Casualty.write.format("orc").saveAsTable("Sex_of_Casualty")
val lookup_make_model_sex_of_driver = sqlContext.read.format("com.databricks.spark.csv").option("header", "true").option("inferSchema", "true").load("/road_safety/datasets/lookups/Sex_of_Driver.csv")
lookup_make_model_sex_of_driver.write.format("orc").saveAsTable("Sex_of_Driver_tab")
val lookup_age_band = sqlContext.read.format("com.databricks.spark.csv").option("header", "true").option("inferSchema", "true").load("/road_safety/datasets/lookups/.csv")
val lookup_Vehicle_Type = sqlContext.read.format("com.databricks.spark.csv").option("header", "true").option("inferSchema", "true").load("/road_safety/datasets/lookups/Vehicle_Type.csv")
lookup_Vehicle_Type.write.format("orc").saveAsTable("lookup_Vehicle_Type")
val data = sqlContext.read.format("com.databricks.spark.csv").option("header", "true").option("inferSchema", "true").load("/road_safety/datasets/lookups/Light_Conditions.csv")
data.registerTempTable("accidents_light_cond")
data.write.format("orc").saveAsTable("accidents_light_cond")
val lookup_rural_urban = sqlContext.read.format("com.databricks.spark.csv").option("header", "true").option("inferSchema", "true").load("/road_safety/datasets/lookups/Urban_Rural.csv")
lookup_rural_urban.write.format("orc").saveAsTable("lookups_2015_area")
val Home_Area_Type = sqlContext.read.format("com.databricks.spark.csv").option("header", "true").option("inferSchema", "true").load("/road_safety/datasets/lookups/Home_Area_Type.csv")
Home_Area_Type.write.format("orc").saveAsTable("Home_Area_Type")
val day = sqlContext.read.format("com.databricks.spark.csv").option("header", "true").option("inferSchema", "true").load("/road_safety/datasets/lookups/Day_of_Week.csv")
day.write.format("orc").saveAsTable("day")
val tab = sqlContext.read.format("com.databricks.spark.csv").option("header", "true").option("inferSchema", "true").load("/road_safety/datasets/2015/road_accident_locations.csv")
tab.write.format("orc").saveAsTable("location")
